### ISSUE TITLE
Discuss what to include in the docker compose

### ISSUE THREAD

**Issue by benhuangbmj** [flushingtech/Votte_Backend#16]
looks great :clap: my only recommendation is to use docker for the postgres db only. encourage running the app locally instead.

_Originally posted by @wilrnh in https://github.com/flushingtech/Votte_Backend/pull/12#pullrequestreview-2480250180_
            
If the app is run locally, the dev would have to set up the `.env` manually.

**Comment by wilrnh** [comment]
yea a common way to share `.env` files is to ship a `.env.example` in the repo, with the same values as you have in the `compose.yml`.

Then, in the README provide instructions for developers to copy `.env.example` to `.env` and replace the dummy values. Remember to add `.env` to the gitignore!

**Comment by benhuangbmj** [comment]
> yea a common way to share `.env` files is to ship a `.env.example` in the repo, with the same values as you have in the `compose.yml`.
> 
> Then, in the README provide instructions for developers to copy `.env.example` to `.env` and replace the dummy values. Remember to add `.env` to the gitignore!

I have no objection to running the app locally. In fact, I’m aware of some subtle downsides to running Node.js from within a container. For example, to get `nodemon` working in the container, I have to use the `--watch` mode. Who knows what other unexpected behaviors might arise? Is this the primary concern behind your proposal? @wilrnh

**Comment by wilrnh** [comment]
yea the main concern is that there are downsides to running the app locally in containers. There's unexpected behaviours, as you mentioned, and also viewing logs is a little different. At some point, you'll also want to run debuggers on the code, which will also be harder to do in a container than directly on your laptop.

**Comment by benhuangbmj** [comment]
> yea the main concern is that there are downsides to running the app locally in containers. There's unexpected behaviours, as you mentioned, and also viewing logs is a little different. At some point, you'll also want to run debuggers on the code, which will also be harder to do in a container than directly on your laptop.

Got you. Thanks. @wilrnh
