### ISSUE TITLE
Setup ORM specifically to help with migrations

### ISSUE THREAD

**Issue by wilrnh** [flushingtech/Votte_Backend#6]
check out drizzle orm

**Comment by benhuangbmj** [comment]
Hi @wilrnh , could you provide a brief update on the progress of this ticket? Once I’ve finished setting up the Docker environment, I’d be very interested in exploring ORM! Thanks!

**Comment by wilrnh** [comment]
Hey thanks for bumping this up for me!

I've got drizzle integrated with votte, it's configuring the db as described in the provided sql. I've just got to clean up done dev data and push a PR, hopefully tonight👍

**Comment by benhuangbmj** [comment]
> Hey thanks for bumping this up for me!
> 
> I've got drizzle integrated with votte, it's configuring the db as described in the provided sql. I've just got to clean up done dev data and push a PR, hopefully tonight👍

Oh, so it sounds like it's almost done! Thanks! I was thinking about joining you and learning how this works though.

**Comment by benhuangbmj** [comment]
Hi @wilrnh , could you create a branch for this issue so that we can see what we can contribute?

**Comment by benhuangbmj** [comment]
PR #18 Add ORM
